### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "Roegan2@gmail.com",
  "password": "123456"
}


### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "Roegan@gmail.com",
  "password": "123456"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find all users in the db
GET http://localhost:3000/auth

### Find a particular user with a given id
GET http://localhost:3000/auth/4

### Find all users with a given email
GET http://localhost:3000/auth?email=emmanuel@gmail.com

### Delete a user wit a given id
DELETE http://localhost:3000/auth/9

### Update a user
PATCH http://localhost:3000/auth/9
content-type: application/json

{
  "email": "jack@gmail.com"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors/